"""add_lable

Revision ID: 4cd65bbc2e1d
Revises: 591ad09e566a
Create Date: 2026-05-01 21:31:14.806245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd65bbc2e1d'
down_revision: Union[str, Sequence[str], None] = '591ad09e566a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('label', sa.String(length=100), nullable=True, comment='YOLO识别标签'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'label')
    # ### end Alembic commands ###
