"""fix_oders

Revision ID: 62ccaba85a07
Revises: 241b12bf1b60
Create Date: 2026-05-01 23:55:17.335211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ccaba85a07'
down_revision: Union[str, Sequence[str], None] = '241b12bf1b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('goods_info', sa.Text(), nullable=True, comment='商品信息列表(JSON)'))
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'single_price')
    op.drop_column('orders', 'goods_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('goods_id', sa.VARCHAR(length=36), nullable=True))
    op.add_column('orders', sa.Column('single_price', sa.REAL(), nullable=False))
    op.add_column('orders', sa.Column('quantity', sa.INTEGER(), nullable=False))
    op.drop_column('orders', 'goods_info')
    # ### end Alembic commands ###
